### PR TITLE
Fix build url

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**

### CODE REVIEW

**Comment by JakeRoggenbuck** [comment]
Before: 
image

**Review by adamhutchings — CHANGES_REQUESTED** [review]
There's another URL messed up, the documentation link at the bottom of README. Would you mind fixing that as well?

**Comment by JakeRoggenbuck** [comment]
> There's another URL messed up, the documentation link at the bottom of README. Would you mind fixing that as well?

Done

**Review by adamhutchings — APPROVED** [review]
Looks good!

**Pull request merged**
