### PR TITLE
Add all crashes and hangs from fuzzer

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**

### CODE REVIEW

**Comment by adamhutchings** [comment]
Do you mind if I go through real quick and rename all of these files to more usable names?

**Comment by JakeRoggenbuck** [comment]
> Do you mind if I go through real quick and rename all of these files to more usable names?

yea, I can do that

**Comment by adamhutchings** [comment]
Probably just `hang1`, `hang2`, etc.

**Review by adamhutchings — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
