### PR TITLE
added testing workflow into its own file

### LINKED ISSUE #86: Separate testing workflow into its own file

### PR DESCRIPTION
**Pull request by RishiKumarRay**
Close #86

### CODE REVIEW

**Comment by RishiKumarRay** [comment]
@adamhutchings hi , actually i thought about this but i was getting errors , to implement this can you please tell me individual commands through which you test and compile , i think then i can separate this.

**Comment by adamhutchings** [comment]
Okay. Then just remove the testing code from compiler.yml and keep the compiling code in testing.

**Comment by Sophon96** [comment]
> @adamhutchings see when i was trying separate this i was getting this error Screenshot from 2022-03-07 22-47-33 maybe i am missing with commands can you tell me

You didn't build the compiler first. You need to build it with cmake first by running `scripts/build.sh` first.

**Comment by adamhutchings** [comment]
I gave wrong advice at first. As you can see, the `valgrind` workflow builds the project before running valgrind. If you simply remove the part where tests are run in the original compiler file, this will be good to go.

**Comment by RishiKumarRay** [comment]
@adamhutchings please check now

**Review by adamhutchings — APPROVED** [review]
Looks good, thank you!

**Comment by JakeRoggenbuck** [comment]
Thanks for contributing! Looks great!

**Pull request merged**
